# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='catch_phrase',
            field=models.CharField(default='LETS GOOOO', max_length=100),
            preserve_default=False,
        ),
    ]
